const styles = {
    // For Pending Card:
    box: {
        backgroundColor: "E9E9E9",

        width: 350,
        height: 90,
        borderRadius: 5,
        padding: 10,
        margin: "auto",
    },
    /* indicator: {
        height: "100%",
        width: "3.5%",
        borderBottomLeftRadius: 5,
        borderTopLeftRadius: 5,
        backgroundColor: "#FFD73F",
        float: "left",
    },*/
    content: {
        width: "22vw",
        paddingLeft: 12,
        height: "100%",
        backgroundColor: "#EEEEEE",
        //float: "right",
        boxShadow: "5px 5px 7px #C0C0C0",
        borderTopRightRadius: 5,
        borderBottomRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderTopLeftRadius: 5,
        alignContent: "center",
    },
    order: {
        backgroundColor: "#DDF3FD",
        height: "23%",
        borderTopRightRadius: 5,
        marginLeft: 4,
        fontWeight: "bold",
        color: "#0477BD",
    },
    item: {
        backgroundColor: "#FFFFFF",
        height: "77%",
        float: "left",
        width: "80%",
        borderRight: "0.5px solid #D0D8DD",
    },
    tick_box: {
        backgroundColor: "white",
        height: "77%",
        width: "19%",
        float: "right",
        borderBottomRightRadius: 5,
        textAlign: "center",
    },
    /*   tick:{
        
        width:30,
        height:30,
        marginTop:17,
        color:'#FFD73F',
        marginLeft:1,
        cursor:'pointer',
        
    },*/
    attribute1: {
        marginTop: 7,
        marginLeft: 15,
        //marginRight: 7,
        height: "35%",
        backgroundColor: "#FFFFFF",
        width: "70%",
        float: "left",
        fontWeight: "bold",
    },
    attribute2: {
        marginTop: 7,
        // marginLeft: 50,

        height: "35%",
        backgroundColor: "white",
        width: "20%",
        float: "left",
    },

    container: {
        backgroundColor: "E9E9E9",
        flexDirection: "column",
    },
    // For Item Card:
    box1: {
        textAlign: "Center",
        color: "#9E9E9E",
        backgroundColor: "#FFFFFF",
        width: "90%",
        height: 100,
        borderRadius: 12,
        padding: 10,
        boxShadow: "12px 12px 16px #C0C0C0",
        margin: "auto",
        display: "flex",
    },
    item1: {
        position: "relative",
        backgroundColor: "#FFFFFF",
        height: "100%",
        float: "left",
        width: "80%",
        textAlign: "center",
        // maxWidth: "25vw",
        display: "flex",
    },
    left_con: {
        height: "100%",
        float: "left",
        width: "65%",
        backgroundColor: "#FFFFFF",
    },
    right_con: {
        height: "100%",
        float: "right",
        width: "35%",
        backgroundColor: "#FFFFFF",
    },
    icon_trash: {
        width: 55,
        height: 40,
        float: "left",
        marginTop: 20,
        color: "#858585",
        cursor: "pointer",
        backgroundColor: "#FFFFFF",
    },
    icon_tick: {
        width: 55,
        height: 40,
        float: "left",
        marginTop: 20,
        cursor: "pointer",
        backgroundColor: "#FFFFFF",
        color: "#00C952",
    },

    attribute3: {
        marginTop: 10,
        marginLeft: 5,
        //marginRight: 7,
        height: "35%",
        backgroundColor: "#EEEEE",
        width: "35%",
        float: "left",
        fontWeight: "bold",
        textAlign: "center",
        color: "#C7C7C7",
    },
    attribute4: {
        marginTop: 10,
        marginLeft: 5,
        //marginRight: 7,
        height: "35%",
        backgroundColor: "#EEEEE",
        width: "60%",
        float: "left",
        fontWeight: "bold",
        textAlign: "center",
        color: "#C7C7C7",
        boxShadow: "0 1px 0px #e9e9e9",
    },
    attribute5: {
        marginTop: 35,
        marginLeft: 20,
        //marginRight: 7,
        height: "35%",
        backgroundColor: "#FFFFFF",
        width: "25%",
        float: "left",
        fontWeight: "bold",
        textAlign: "center",
        color: "#C7C7C7",
    },
    attribute6: {
        marginTop: 35,
        marginLeft: 5,
        //marginRight: 7,
        height: "35%",
        backgroundColor: "#FFFFFF",
        width: "25%",
        float: "left",
        fontWeight: "bold",
        textAlign: "center",
        color: "#C7C7C7",
        boxShadow: "0 1px 0px #e9e9e9",
    },
    edit_button: {
        backgroundColor: "#FFFFFF",
        width: 110,
        height: 30,
        marginTop: 65,
    },

    wrap: {
        backgroundColor: "#FFFFFF",
        width: 110,
        height: 100,
        float: "left",
    },

    input: {
        border: "white",
        borderTop: "white",
        borderLeft: "white",
        marginLeft: 20,
        color: "#9E9E9E",
        boxShadow: "0 1px 0px #e9e9e9",
        backgroundColor: "yellow",
    },
    input2: {
        border: "white",
        borderTop: "white",
        borderLeft: "white",
        width: 50,
        marginLeft: 20,
        color: "#9E9E9E",
        boxShadow: "0 1px 0px #e9e9e9",
        backgroundColor: "blue",
    },

    nameinput: {
        marginTop: 7,
        marginLeft: 7,

        height: "35%",
        backgroundColor: "white",
        width: "20%",
        float: "left",
    },

    /*  attribute3: {
       fontWeight: "bold",
        marginTop: 7,
    marginLeft: 80,
        marginRight: 7,
        height: '35%',
        
        width: '70%',
        float: 'left',
        backgroundColor:'red',
    },
    attribute4: {
        position: "absolute",
        top: "50%",
        transform: "translateY(35%)",
        left: 350,
        fontWeight: "bold",
        height: '35%',
        width: '50%',
        float: 'left',
        backgroundColor:'grey',
    },
    attribute5: {
        marginTop: 7,
        marginLeft: 35,
        marginRight: 7,
        height: '35%',
        backgroundColor: 'white',
        // width: '70%',
        float: 'left',
        fontWeight: "bold",
        
    },*/
    head_category: {
        height: 70,
        paddingLeft: 15,
        paddingRight: 15,
        borderRadius: 0,
    },
    main_category: {
        fontSize: 27,
        paddingTop: 15,
        paddingLeft: 5,
        color: "#607D8B",
    },
    icon_plus: {
        float: "right",
        fontSize: 30,
        color: "#019BE5",
        padding: 10,
        top: "0%",
        transform: "translateY(-81%)",
    },
    ordersToolbar: {
        justifyContent: "space-between",
    },
    //smaller trapezium:
    firstColorsm: {
        backgroundColor: "#0477BD",
        color: "white",
        textAlign: "center",
        height: "90%",
        width: "15%",
        margin: 0,
        float: "left",
        borderRadius: 0,
        clipPath: "polygon(15% 0%, 85% 0, 100% 100%, 0% 100%)",
        position: "absolute",
        bottom: 0,
        left: 0,
        zIndex: 2,
    },
    firstsm: {
        backgroundColor: "#EEEEEE",
        textAlign: "center",
        height: "90%",
        width: "15%",
        margin: 0,
        float: "left",
        borderRadius: 0,
        clipPath: "polygon(15% 0%, 85% 0, 100% 100%, 0% 100%)",
        position: "absolute",
        bottom: 0,
        color: "0477BD",
        left: 0,
        zIndex: 1,
    },
    secondsm: {
        backgroundColor: "#EEEEEE",
        // outline: "solid 3px #9E9E9E",
        height: "90%",
        width: "15%",
        float: "left",
        margin: 0,
        borderRadius: 0,
        clipPath: "polygon(15% 0%, 85% 0, 100% 100%, 0% 100%)",
        position: "absolute",
        bottom: 0,
        left: "14.25%",
        zIndex: 1,
    },
    secondColorsm: {
        backgroundColor: "#0477BD",
        // outline: "solid 3px #9E9E9E",
        height: "90%",
        width: "15%",
        float: "left",
        margin: 0,
        borderRadius: 0,
        clipPath: "polygon(15% 0%, 85% 0, 100% 100%, 0% 100%)",
        position: "absolute",
        bottom: 0,
        left: "14.25%",
        zIndex: 1,
        color: "white",
    },
};

export default styles;
