# Generated by Django 2.2.4 on 2019-08-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenDb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
