# Generated by Django 2.2.4 on 2019-08-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenDb', '0002_auto_20190826_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='transaction_fees',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_choices',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
