# Generated by Django 2.2.4 on 2019-08-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenDb', '0003_auto_20190826_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
