# Generated by Django 2.1.4 on 2018-12-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("canteenWeb", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="canteenWeb.Order"
            ),
        )
    ]
