# Generated by Django 2.0.5 on 2018-12-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteenWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='division',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='floor',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='EMAIL_FIELD',
            field=models.EmailField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='USERNAME_FIELD',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
    ]
