# Generated by Django 2.1.4 on 2018-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
